const main = async () => {

  // http://127.0.0.1:7545
};

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.log(err)
    process.exit(1);
  });
